[package]
edition = "2021"
name = "napi-pnpm"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.16.0", default-features = false, features = ["napi4"] }
napi-derive = "2.16.0"
napi_pnpm_core = { version = "0.0.0", path = "../../crates/core" }

[build-dependencies]
napi-build = "2.1.2"

[profile.release]
lto = true
strip = "symbols"
